---
title: "Milestone 4 gathering data"
author: "Fahad Alkhaja"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(StatsBombR)
library(tidyverse)

```

```{r readin_sample_tracking_data}
# After inspecting the data, I realized I had to skip two rows.
Sample_Game_1_RawTrackingData_Home_Team <- read_csv("sample_data/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Home_Team.csv",
          skip = 2,
          col_types = cols(.default = col_double()))

Sample_Game_1_RawTrackingData_Away_Team <- read_csv("sample_data/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv",
          skip = 2,
          col_types = cols(.default = col_double()))

```
```{r get_ball_data}
# The ball_data is included in both the home and away team tracking data
# I simply had to select the final two rows of either the home or away team csv files
ball_data <- Sample_Game_1_RawTrackingData_Home_Team %>%
  select(Ball, X33)

```

```{r readin_raw_event_data}

Sample_Game_1_RawEventsData <- read_csv("sample_data/data/Sample_Game_1/Sample_Game_1_RawEventsData.csv",
          col_types = cols(Team = col_character(),
                           Type = col_character(),
                           Subtype = col_character(),
                           Period = col_double(),
                           `Start Frame` = col_double(),
                           `Start Time [s]` = col_double(),
                           `End Frame` = col_double(),
                           `End Time [s]` = col_double(),
                           From = col_character(),
                           To = col_character(),
                           `Start X` = col_double(),
                           `Start Y` = col_double(),
                           `End X` = col_double(),
                           `End Y` = col_double() ))
```

```{r saveRDS}
# Uncomment so we dont keep overwriting.

# gather <- Sample_Game_1_RawEventsData

# saveRDS(gather, "Milestone_4/gather.RDS")
```

